// let departments = [
//   "Physical Therapy Assistant",
//   "Physical Therapy Assistant",
//   "Accountant III",
//   "Help Desk Technician",
//   "Account Executive",
//   "Senior Cost Accountant",
//   "Editor",
//   "Web Developer II",
//   "Food Chemist",
//   "Librarian",
//   "Media Manager IV",
//   "Web Developer II",
//   "VP Product Management",
//   "Accountant IV",
//   "Geological Engineer",
//   "Nurse Practicioner",
//   "Help Desk Operator",
//   "Speech Pathologist",
//   "Sales Representative",
//   "Staff Scientist",
//   "Budget/Accounting Analyst II",
//   "VP Quality Control",
//   "Administrative Officer",
//   "Human Resources Assistant III",
//   "Recruiting Manager",
//   "VP Product Management",
//   "Technical Writer",
//   "Executive Secretary",
//   "Quality Engineer",
//   "Junior Executive",
//   "Product Engineer",
//   "Administrative Officer",
//   "Marketing Assistant",
//   "Legal Assistant",
//   "Director of Sales",
//   "Quality Engineer",
//   "Programmer Analyst II",
//   "Senior Sales Associate",
//   "Biostatistician III",
//   "Senior Developer",
//   "Financial Advisor",
//   "Administrative Officer",
//   "Developer IV",
//   "Business Systems Development Analyst",
//   "Research Assistant I",
//   "Software Consultant",
//   "Web Designer II",
//   "Programmer Analyst II",
//   "VP Accounting",
//   "Clinical Specialist",
//   "Operator",
//   "VP Product Management",
//   "Software Engineer II",
//   "Financial Advisor",
//   "Paralegal",
//   "Help Desk Operator",
//   "Quality Control Specialist",
//   "Desktop Support Technician",
//   "Environmental Specialist",
//   "Office Assistant I",
//   "Assistant Manager",
//   "Programmer I",
//   "VP Accounting",
//   "Biostatistician III",
//   "Senior Editor",
//   "Biostatistician I",
//   "Assistant Media Planner",
//   "Financial Analyst",
//   "Quality Engineer",
//   "Physical Therapy Assistant",
//   "Senior Cost Accountant",
//   "Director of Sales",
//   "Automation Specialist III",
//   "Financial Analyst",
//   "Assistant Media Planner",
//   "Environmental Specialist",
//   "Senior Quality Engineer",
//   "Civil Engineer",
//   "Speech Pathologist",
//   "Librarian",
//   "Accounting Assistant IV",
//   "General Manager",
//   "Staff Accountant III",
//   "Software Consultant",
//   "Recruiter",
//   "Registered Nurse",
//   "Database Administrator I",
//   "Legal Assistant",
//   "Sales Associate",
//   "Assistant Manager",
//   "Geological Engineer",
//   "Systems Administrator I",
//   "Assistant Manager",
//   "Financial Analyst",
//   "Help Desk Technician",
//   "Assistant Media Planner",
//   "Financial Analyst",
//   "Senior Developer",
//   "Legal Assistant",
//   "Research Associate",
// ];
// let newDepartments = new Set(departments);
// let num = 0;
// num++;

// let newdepartments = departments.map((item, index) => ({
//   id: index + 1,
//   name: item,
//   leader: "Yasser",
// }));
// console.log(newdepartments);

// for (let i = 1; i <= 250; i++) {
//   let o = {
//     userId: Math.floor(Math.random() * 250),
//     id: i,
// days: [
//   { id: 1, day: "2023-08-1", attend: true, icon: "✔" },
//   { id: 2, day: "2023-08-2", attend: true, icon: "✔" },
//   { id: 3, day: "2023-08-3", attend: true, icon: "✔" },
//   { id: 4, day: "2023-08-4", attend: true, icon: "✔" },
//   { id: 5, day: "2023-08-5", attend: false, icon: "❌" },
//   { id: 6, day: "2023-08-6", attend: true, icon: "✔" },
//   { id: 7, day: "2023-08-7", attend: true, icon: "✔" },
//   { id: 8, day: "2023-08-8", attend: true, icon: "✔" },
//   { id: 9, day: "2023-08-9", attend: true, icon: "✔" },
//   { id: 10, day: "2023-08-10", attend: true, icon: "✔" },
//   { id: 11, day: "2023-08-11", attend: true, icon: "✔" },
//   { id: 12, day: "2023-08-12", attend: false, icon: "❌" },
//   { id: 13, day: "2023-08-13", attend: true, icon: "✔" },
//   { id: 14, day: "2023-08-14", attend: true, icon: "✔" },
//   { id: 15, day: "2023-08-15", attend: true, icon: "✔" },
//   { id: 16, day: "2023-08-16", attend: true, icon: "✔" },
//   { id: 17, day: "2023-08-17", attend: false, icon: "❌" },
//   { id: 18, day: "2023-08-18", attend: true, icon: "✔" },
//   { id: 19, day: "2023-08-19", attend: true, icon: "✔" },
//   { id: 20, day: "2023-08-20", attend: false, icon: "❌" },
//   { id: 21, day: "2023-08-21", attend: true, icon: "✔" },
//   { id: 22, day: "2023-08-22", attend: true, icon: "✔" },
//   { id: 23, day: "2023-08-23", attend: false, icon: "❌" },
//   { id: 24, day: "2023-08-24", attend: true, icon: "✔" },
//   { id: 25, day: "2023-08-25", attend: false, icon: "❌" },
//   { id: 26, day: "2023-08-26", attend: false, icon: "❌" },
//   { id: 27, day: "2023-08-27", attend: true, icon: "✔" },
//   { id: 28, day: "2023-08-28", attend: false, icon: "❌" },
//   { id: 29, day: "2023-08-29", attend: true, icon: "✔" },
//   { id: 30, day: "2023-08-30", attend: true, icon: "✔" },
// ],
//   };
//   console.log(o);
// }
