"use client";
import "./globals.scss";
import { Inter } from "next/font/google";
import { Providers } from "../redux/Providers";
import { Toaster } from "react-hot-toast";
const inter = Inter({ subsets: ["latin"] });
import Navbar from "../components/Navbar";
export const metadata = {
  title: "Tenor",
  description: "Generated by Yasser Alnajjar",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />
      </head>
      <body className={inter.className}>
        <Toaster position="top right" />
        <Providers>
          <Navbar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
