"use client";
import "./globals.css";
import { Inter } from "next/font/google";
import { Providers } from "../redux/Providers";
import { AiOutlineArrowUp } from "react-icons/ai";
import { Button } from "react-bootstrap";
import { Toaster } from "react-hot-toast";

import Layout from "../components/Layout";
import Sidebar from "../components/Shared/Sidebar";
import NavbarFC from "../components/Shared/NavbarFC";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Tenor",
  description: "Generated by Yasser Alnajjar",
  author: "Yasser Alnajjar",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />
      </head>
      <body className={inter.className}>
        <Providers>
          <Layout>
            <div className={" d-flex"}>
              <Sidebar />
              <div className="w-100">
                <Toaster
                  toastOptions={{
                    duration: 4000,
                    position: "right-top",
                    style: {},
                    className: `shadow`,
                  }}
                />
                <div>{children}</div>
                <div
                  className="position-fixed"
                  style={{
                    bottom: "30px",
                    right: "30px",
                  }}
                >
                  <Button variant="warning" onClick={() => scrollTop()}>
                    <AiOutlineArrowUp />
                  </Button>
                </div>
              </div>
            </div>
          </Layout>
        </Providers>
      </body>
    </html>
  );
}
